_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 53
                - 55
                - 71
                - 105
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.11
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
